[build]
  command = "mkdir -p dist && cp src/index.html dist && cp src/app.jsx dist && cp public/leaderboard.json dist"
  publish = "dist"

[[redirects]]
  from = "/leaderboard.json"
  to = "/leaderboard.json"
  status = 200
